# OctoDNS config file for the Main DNS system of zones.
---
providers:
  main:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/
    enforce_order: False
   bind:
      class: octodns_bind.BindProvider
      # The address of nameserver to perform zone transfer against
      host: 100.64.0.2
      # The port that the nameserver is listening on. Optional. Default: 53
      port: 53
      # The number of seconds to wait until timing out. Optional. Default: 15
      timeout: 15
      # optional, default: non-authed
      key_name: octodns
      # optional, default: non-authed
      key_secret: env/BIND_SECRET
      # optional, see https://github.com/rthalley/dnspython/blob/master/dns/tsig.py#L78
      # for available algorithms
      key_algorithm: hmac-sha1
#
#
#
zones:
  purplebubble.org.:
    sources:
      - main
    targets:
      - ns1
