name: DNS Deploy/Sync (OctoDNS)

on:
  push:
    branches:
      - main

jobs:
  OctoDNS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip" # caches pip dependencies
      - run: pip install -r requirements.txt
      - name: Confirm installation
        run: |
          python -c "import octodns; import octodns_cloudflare"
      - name: Set execute permissions
        run: |
          chmod +x ./bin/sync
      - name: Sync w/ production DNS providers
        run: ./bin/sync
        env:
          NS1_API_KEY: ${{ secrets.NS1_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
